// <auto-generated />
using Microsoft.EntityFrameworkCore;
using Microsoft.EntityFrameworkCore.Infrastructure;
using Microsoft.EntityFrameworkCore.Metadata;
using Microsoft.EntityFrameworkCore.Storage.ValueConversion;
using SimpleCalculator.Models;

namespace SimpleCalculator.Migrations
{
    [DbContext(typeof(CalculationDbContextClass))]
    partial class CalculationDbContextClassModelSnapshot : ModelSnapshot
    {
        protected override void BuildModel(ModelBuilder modelBuilder)
        {
#pragma warning disable 612, 618
            modelBuilder
                .HasAnnotation("ProductVersion", "3.1.28")
                .HasAnnotation("Relational:MaxIdentifierLength", 128)
                .HasAnnotation("SqlServer:ValueGenerationStrategy", SqlServerValueGenerationStrategy.IdentityColumn);

            modelBuilder.Entity("SimpleCalculator.Models.Calculation", b =>
                {
                    b.Property<decimal>("First_Number")
                        .HasColumnType("decimal(18,2)");

                    b.Property<string>("Operator")
                        .HasColumnType("nvarchar(max)");

                    b.Property<decimal>("Result")
                        .HasColumnType("decimal(18,2)");

                    b.Property<decimal>("Second_Number")
                        .HasColumnType("decimal(18,2)");

                    b.HasKey("First_Number");

                    b.ToTable("Calculations");
                });
#pragma warning restore 612, 618
        }
    }
}
